import "./globals.css";
import { Kalam, Patrick_Hand } from "next/font/google";
import { Toaster } from "react-hot-toast";
const kalam = Kalam({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-kalam",
});

const patrickHand = Patrick_Hand({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-patrick",
});

export const metadata = {
   title: "Draw with Bingus",
  description: "Generated by create next app",
};
export const viewport = {
  width: "device-width",
  initialScale: 1,
}

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${kalam.variable} ${patrickHand.variable}`}
    >
      <body className="min-h-screen flex flex-col">
        {children}
        <Toaster position="top-center" />
      </body>
    </html>
  );
}
